### ISSUE TITLE
Trello functionality for bot

### ISSUE THREAD

**Issue by rufuspollock** [datopian/ourbot#23]
We want to have our bot to function with Trello

## Acceptance criteria
 
* [ ] Written Trello analysis 

## Tasks

* [ ] Write analysis for Trello functionality #71 
* [ ] Read the analysis and come up with tasks
