### ISSUE TITLE
Review MVP as is 17 March 2017

### ISSUE THREAD

**Issue by rufuspollock** [datopian/ourbot#3]
Check out the code as it is so far and evaluate it against the acceptance criteria so that we can know how close to finished we are and highlight any gaps and improvements.

## Tasks

* [x] Install yourself and run tests
* [ ] Deploy to our heroku
* [x] Compare against acceptance criteria and give feedback (copy acceptance criteria and annotate here)
* [x] Provide general feedback on code quality, linting etc

Things to test:

* [x] Can I log from main channel +todo to a google docs
* [x] Ditto for a gist
* [x] Can I do both at once (log + todo to both google docs and a gist)
* [x] Can I log from multiple channels and configure different behaviour (e.g. log +todo from one room to gdocs and log +todo from other room to gist)

**Comment by zelima** [comment]
@weirdGuy Going through the code:

## configurations

Epic: https://github.com/atomatichq/ourbot/issues/6

required specifications: 
```
// some of this should be auto loaded from environment variables (so we can config on heroku)

// config.json
{
  github_auth:
  gdocs_auth:
  docs: {
    "gist1": {
      "type": "gist"
    }
    "gdocs1": {
      "type": "gdocs"
    }
  }
  monitor: {
    "+todo": {
      "action"": "log",
      "dest": "gist1"
    },
    "+standup": ...
  }
}
```
- All the variables (including sensitive) are set into `config.json` and used from there. We should load some of them (sensitive ones) form environment variables. Other way we have to deploy to heroku our `config.json` , but that is not an option. 
- I don't see any configurations (or instructions) for gist, therefore I assume, we do not support logging into gist yet
- As we don't support gist yet, probably we don't support configurable docs for logging `{docs: {gist1: ... }}`
- I see "key words" to monitor are not configurable as well and are hard coded https://github.com/atomatichq/ourbot/blob/master/scripts/example.coffee#L24
  - What if I want to add new key word Eg: `+meeting` or something
  - what if I want to get from room N1 only +todos and  +standups from roomN2

## Tests

https://github.com/atomatichq/ourbot/issues/10

- Looking at the tests, now I see we are not actually testing anything, but chat room "geathering" all the messages: https://github.com/atomatichq/ourbot/blob/master/scripts/example.coffee#L24
  - also from where that other response came from ? :) https://github.com/atomatichq/ourbot/blob/master/test/example-test.js#L22
- Are we actually testing anything in [messages-test.js](https://github.com/atomatichq/ourbot/blob/master/test/messages-test.js), cause I don't see any assertion or expectations there... Are we just testing that it is not throwing errors?
- Generally speaking we need more specific tests
  - test messaging works fine
  - test bot is catching +keywords works fine
  - test bot is not catching +someother that is not pre defined
  - test bot is not retrieves all the necessary info from message Eg: time, user, message, room etc..
  - test message is actually logged / saved somewhere (locally)

## scripts

https://github.com/atomatichq/ourbot/issues/11

- why this script is called [example.coffee](https://github.com/atomatichq/ourbot/blob/master/scripts/example.coffee)
- Not sure I think we don't need anything after [line 29](https://github.com/atomatichq/ourbot/blob/master/scripts/example.coffee#L29) in example.coffee  maybe [line 60](https://github.com/atomatichq/ourbot/blob/master/scripts/example.coffee#L29) for tests?
- I see we are using ES6 for JS - Eg: `import` , `let` syntax. Can we stay consistent? Eg: use let / const instead of var as needed https://github.com/atomatichq/ourbot/blob/master/scripts/messages.js#L23 . Also use arrow functions where apropriate

**Comment by zelima** [comment]
FIXED. closing as review is done and new issues are open
Excuding deployment to Heroku, as to do this we need to first fix issue with exposing sensitive variables

**Comment by rufuspollock** [comment]
I hear you @zelima but here I'd like to keep this open until the MVP is really done -- all related issues are fixed - this is the epic and should stay open until all associated items are done.

**Comment by rufuspollock** [comment]
FIXED. Confused this with #1! Actually this is done.

**Comment by zelima** [comment]
### instructions, suggestons and better practice after analyzing "code review" above: 

```bash
# .env

# AUTH
GOOGLE_PRIVATE_KEY="<long_private_key>",
GOOGLE_CLIENT_EMAIL="<key_email>",

GITHUB_...
```

Routing Config

```
// config.json
{
  docs: {
    "gist1": {
      "type": "gist"
      "url": ...
    }
    "gdocs1": {
      "type": "gdocs"
      "worksheet": ...
    }
  }
  monitors: [
    {
      "room": "datopian/dev"
      "term": "+todo",
      "action"": "todolog",
      "doc": "gist1"
    },
    {
      "room": "datopian/dev",
      "term": "+standup",
      "action": "standuplog",
      "doc": "gdocs1"
    },
    ..
}
```

```mermaid
graph TD

  listen[Listen for message] --> parse[Parse messsage to std structure]
  parse --> logger[Convert to log message for appropriate output]
  logger --> output[Output e.g. GDocs or Gist]
```

* Parse: ... 
* 2 loggers: todo and standup
  * todo does nothing - passed through the structure
  * standup: converts `{ ... }` to a string
* 2 writers
  * GDocs
  * Gist - stringify what it is given and appends it ... 

```javascript=
// another answer create a regex that you want
// myregex = '(.*+todo.*)|(.*+.*)'

  // listen to everything
  robot.hear '/*/', res
    // do your own regex here ...
    for monitor in monitors:
      ....
```

## Testing

https://github.com/blalor/hubot-mock-adapter

What you want to test - and do each of these independently:

* You extract messages from the channel(s)
  * You act on messages with an action and ignore those that don't
* You parse those messages to a correct structure
  * e.g. xxx @abc +todo => `{ .... }`
* You act on those messages in the right way e.g. you log to gist or doc
  * You parse and use the routing config correctly

You want to mock the code ...

* Connecting to the room and getting messages
* Mock out google docs or github API and check you get messages sent

Example using nock:

https://github.com/frictionlessdata/dpr-js/blob/gh-pages/tests/utils/datapackage.test.js

https://github.com/node-nock/nock

```
robot._saveToGoogleDoc(message)

mock(robot._saveToGoogleDoc, myStubFunction)
```
