### ISSUE TITLE
Format options for Gist 

### ISSUE THREAD

**Issue by zelima** [datopian/ourbot#39]
Currently we are logging in `log.txt` gist without any formatting.

## Acceptance criteria

- [ ] logs are in desired format

## Tasks 

- [ ] decide which of two options below is better
- [ ] Update test appropriately
- [ ] refactor code appropriately
- [ ] update README if needed

## Options:

* [ ] todo.csv (with format like now but maybe need to watch out for quoting the descripting field)
* [ ] a markdown file with format like:
```
* [ ] yyyy-mm-dd @name {description}
* [ ]
 ```
