### ISSUE TITLE
Adding bot to the rooms

### ISSUE THREAD

**Issue by zelima** [datopian/ourbot#40]
Currently we are manually adding boot to all of the rooms. we wan't bot auto-adding itself to room (or adding itself to rooms listed in config.json)

## Acceptance criteria

- [ ] Clear analysis done here (after **Tasks** section)
- [ ] if possible we can set room name(s) in `config.json` and bot adds itself to it

## Tasks

- [x] Do analysis and see hubot docs. Find if bot can add itself to rooms 
- [ ] If yes, list out what options do we have
- [ ] Create tests for it
- [ ] Update code appropriately

## Analysis

TODO

**Comment by Mikanebu** [comment]
I could not find information about adding hubot into room automatically, checked out `hubot-gitter` and `hubot-gitter2` packages.

**Comment by zelima** [comment]
@Mikanebu could you please close this as WONTFIX if it is not possible and probably provide links to hubot-gitter docs

**Comment by Mikanebu** [comment]
WONTFIX. No proper documentation for adding rooms automatically: https://github.com/huafu/hubot-gitter2
https://github.com/kcjpop/hubot-gitter
