### ISSUE TITLE
Prepend new todo's in the Google spreadsheet instead of appending

### ISSUE THREAD

**Issue by zelima** [datopian/ourbot#42]
Currently every new `+todo` (or any other log) is written on new line in google Spreadsheet. Eg: if latest entry is on line 10 next `+todo` will come on line 11. The more time passes longer the spreadsheet becomes and at some point it will be hard to find the latest todo's as user has to scroll all the way down. Would be great if new `+todo` appears on first line and others will shift down. 

## Acceptance criteria

- [ ] every new `+todo` appears right after header (2nd or 3rd) line

## Tasks

- [x] Do analysis and find out how hard is that to implement
- [ ] write tests (if possible)
- [ ] implement 

## Analysis 

Our bot is using `node-google-spreadsheet`  library and there is no support for prepending line https://github.com/theoephraim/node-google-spreadsheet/issues/127.  There are several libraries that words with Google Spreadsheet such as `google-spreadsheet-append`. If there is no API for prepending row, this needs to be closed as `WONTFIX`

**Comment by Mikanebu** [comment]
WONT FIX, there is not prepend method in official google API documentation
