### ISSUE TITLE
Add help command for ourbot

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#48]
We want to have help command for our bot to see what kind of functionality it has. 

## Acceptance criteria

* [x] Default to help command if either `bot help` or just `bot`

## Tasks

* [x] Add respond function for bot to see all the possible command
* [x] Update `README.md` by adding heading for bot commands
* [x] Added unittest for `bot` command help messages

**Comment by Mikanebu** [comment]
FIXED, we have the following command for bot help: `bot`, `/bot`, `bot help`, `/bot help`.
