### ISSUE TITLE
+link command

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#50]
As Meiran I want to post a link to e.g. a piece of software or a blog post and tag it with +link and have it captured so that I can easily find it later

* Atm have dedicated link channel but useful just to do this in a given channel
* Listen for +link and record it ...
  * This would be a trivial mod of the +todo list item

## Acceptance criteria

* [x] `+link` in any part of sentence trigger bot to record data into gdocs
* [x] `bot links` will return url of  gdocs where our link is recorded

## Tasks

* [x] analysis for realization 
* [x] update `config.json`
* [x] refactor `messages.js` to use different sheet in gdocs
* [x] add new funtion to hear `bot links`
* [x] test it locally in our `bot` channel
* [x] update `README.md`
* [x] write unittest 
* [x] push to heroku

## Analysis

`config.json` is a good place to take a lot, how our `+todo` is realized. 
```javascript=
{
    "monitor": {
        "+todo": {
            "action": "log",
            "dest": ["gdoc1", "gist1"]
        },
        "+standup": {
            "action": "log",
            "dest": ["gdoc1"]
        },
        "+example": {
            "action": "log",
            "dest": ["gdoc2"]
        },
        "+link": {
           "action":"log",
           "dest":["gdoc3]
        }
    }
}
```
We can add another property into `monitor`, and provide with `action` and `dest`

We are going to use the same spreadsheet, but the different sheet.

The logic will be same as in `+todo`: 

In your chat channel tag at start, middle or end of a message: `+link`

```
+link ...
...  +link ...

... +link
```
This will get logged to the Google doc with the following format:
```
action, timestamp, poster, assignees, message, room
+link,yyyy-mm-ddTHH:MM,@{username}(name),@{username},your message,roomname
```
In addition, we will add bot command:
```
bot links - it will reply with gdocs url
```

**Comment by rufuspollock** [comment]
@Mikanebu 

* Title has +link**s** but issue is about +link is this difference intentional?
* User story is pretty clear but would be nice to have properly e.g. "As Meiran I want to post ..."
* Needs acceptance criteria and the tasks (and any additional analysis)
* Needs the time estimate

**Comment by Mikanebu** [comment]
@rufuspollock Corrected title, it is `+link`. Do we need to save them in new gist and gdocs or same sources we used for `+todo`?

**Comment by Mikanebu** [comment]
FIXED
