### ISSUE TITLE
Open and close milestone by bot

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#51]
We want to close and open milestones by bot command

## Acceptance criteria

* [x] `bot create milestone all "title"` will create a milestone in all repos in the list
  list - list of objects in following format `{owner: 'datahq', repo: 'docs'}, {}..`
* [x] `bot close milestone "title" `will close a milestone in all repos in the list
* [x] `bot create milestone "name" in "myorg/myrepo"` - create for single repos
* [x] `bot close milestone "name" in "myorg/myrepo"` - close for single repos

## Tasks

* [x] Read configuration file `config.json` and how it works 
* [x] Do analysis how we can use it in providing `list`
* [x] get GitHub token to create a milestone
* [x] create function `hear` in `main.js`
* [x] create separate file`milestone.js` with 4 functions: createMilestone, closeMilestone, createMilestoneAll, closeMilestoneAll
* [x] write unittest
* [x] update `README.md`
* [x] test locally in `bot` channel
* [x] push to heroku

## Analysis

commands to implement:
### Without providing repo name will create milestone in all repos in the `config.json`: 
```
bot create milestone all "title"
bot close milestone all "title"
```
This is how `config.json` will look like: 
```
{
  "repos": [
      {"owner": "datahq", "repo": "docs"}
   ]
}
```
### to create or close for single repos
```
bot create milestone "title" in  "myorg/myrepo" 
bot close milestone "titile" in "myorg/myrepo"
```

For all other commands, the bot will not respond. It is required to follow that structure and syntax. 
`title`- title of the milestone, for example, 11 Sep 2017

To implement the abovementioned command, we need to have the following requirements:
* token in GitHub to create and close milestones
* Datopianbot should be in each organization to create a milestone. 
I checked, bot is able to create milestones in `datahq`, datopian` and `frictionlessdata`. 

We can /hear gitter channel for these words, if matches, we can run by refactoring our code in `extras/createMilestone.js` and `extras/closeMilestones

Documentation for GitHub API calls can be found here: http://github-tools.github.io/github/docs/3.1.0/Issue.html#createMilestone

**Comment by zelima** [comment]
@Mikanebu this is great! 

can you also explain about which list are you talking about? Where is that list located? In the configurations? 

Also, Would it be also possible to close/open milestone for specified repo Eg: `bot create milestone <name/title> <myorg/myrepo>`

**Comment by Mikanebu** [comment]
@zelima updated

**Comment by rufuspollock** [comment]
@Mikanebu quick suggestions:

A. Change `<name/title>` to `<name>` it will make it clear that `/` is not a separator but an optional item (i'd use `|` for options in future) and that this is not like `<myorg/myname>`

B. I'd like to understand the list format - i think this is going to be common for other work. My suggestion is that you have a CSV or Tabular JSON of repos and then group those in some manner (either in a separate object or by tagging in the original list).

**Comment by Mikanebu** [comment]
@rufuspollock It is going to be in JSON format, hubot has a configuration file `config.json`. I will provide exampes in analysis section

**Comment by Mikanebu** [comment]
FIXED
