### ISSUE TITLE
disable logging +todo to gist

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#54]
We, now have a bot command `+todo` which logs data into `gist` and `gdocs`. We want to disable logging to gist. 

## Acceptance criteria

* [x] `+todo` only logs into gdocs

## Tasks

* [x] Remove  `gist1` from the `config.json`
* [x] Test it locally on `bot` channel
* [x] Remove gist url from the `bot todos`
* [x] Push to heroku

**Comment by Mikanebu** [comment]
FIXED
