### ISSUE TITLE
[Epic] refactor config.json as required in specifications

### ISSUE THREAD

**Issue by zelima** [datopian/ourbot#6]
Current look of `config.json`:
```
{
    "type": "service_account",
    "project_id": "<project_id>",
    "private_key_id": "<key_ID>",
    "private_key": "<long_private_key>",
    "client_email": "<key_email>",
    "client_id": "<client_id>",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://accounts.google.com/o/oauth2/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/941963576311-compute%40developer.gserviceaccount.com",
    "workSheet": "<workSheet_for_table>"
}
```
currently it is used to set google docs configurations and only.

## proposal

we need config.json to follow specifications like this
```
{
  github_auth:
  gdocs_auth:
  docs: {
    "gist1": {
      "type": "gist"
    }
    "gdocs1": {
      "type": "gdocs"
    }
  }
  monitor: {
    "+todo": {
      "action"": "log",
      "dest": "gist1"
    },
    "+standup": ...
  }
}
```
- [x] sensitive info like above should be loaded from environment variables https://github.com/atomatichq/ourbot/issues/7
- [x] should accept configurable `docs` parameter to specify where I want to save logs  https://github.com/atomatichq/ourbot/issues/8
- [x] should accept configurable `monitor` parameter to specify what key words I want to "filter" chat by https://github.com/atomatichq/ourbot/issues/9

**Comment by weirdGuy** [comment]
70ee7f6 Environment variables added

**Comment by weirdGuy** [comment]
FIXED.
All the config.json formatting as required in specification
