### ISSUE TITLE
linter for our bot

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#60]
We want to have code quality tool that checks for problems in Javascript programs

## Acceptance criteria 

* [x] Installed lint `xo` and fixed errors

## Tasks

* [x] Install `xo` 0.1
* [x] setup configuration in `package.json` 0.3
* [x] fix errors 2
* [x] add `lint` command into `travis.yml` 0.1

## Analysis

We use [xo](https://github.com/sindresorhus/xo) for checking code quality. It is popular and constantly updated, plus, our other libraries already use. 
Add to `travis.yml`:
```
before_deploy: npm lint
```
In `package.json` it will look like 
```
"scripts": {
    "lint": "xo --quiet",
  },
```

**Comment by Mikanebu** [comment]
FIXED, now we can `lint` command to check code quality. Just run `npm run lint` or `npm test`
