### ISSUE TITLE
Fefactor help command

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#61]
We want to refactor help command to remove `hubot-help` library and use our own help commands written in markdown. 

## Acceptance criteria

* [x] `bot|/bot {help}` shows help message 

## Tasks 

* [x] remove `hubot-help` from `package.json`
* [x] create `docs/help.md` - markdown with help messages
  * [x] add section `tags`
  * [x] add section `commands`
* [x] refactor main.js to use `docs/help.md`
* [x] remove unused packages from `external-scripts.json` and from `package.json`
## Analysis

`hubot-help` is uses libraries in our `external-scripts.json` and it only shows commands.
```
  "hubot-diagnostics",
  "hubot-google-images",
  "hubot-google-translate",
  "hubot-heroku-keepalive",
  "hubot-pugme",
  "hubot-maps",
  "hubot-rules",
  "hubot-shipit"
```
Commands like `bot animate me, bot image me, bot translate me` are not working, because that are not configured in our `bot` library. 
Since we are adding more commands to our bot, we have to add commands into list in `bot help`. 
Easy way to remove it from out library and create `docs/help.md`.

**Comment by Mikanebu** [comment]
FIXED
