### ISSUE TITLE
Misc improvement from bot demo on 29.08.2017

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#64]
We want to have fixed the following report on 29.08.2017 after bot demo
* remove bot adapter
* bot issue:
  * bot issue should respond with a direct link to created issue (link to what?)
  * extra ` sign in response after creating issue
  * able to create an issue without description
* bot should generally respond after doing +todo or +link
* bot should respond with specific timezone, e.g., bot time almaty and it should return time in almaty - moved into separate issue #65 
* title` in create milestone should be as in close milestone
* `bot links` will return Google Spreadsheet URL moved into #50 

## Acceptance criteria

* [x] `bot adapter` command removed from the help
* [x] `bot create` issue
  * [x] will return exact link to the created issue after running command
  * [x] extra typo is fixed
  * [x] `bot issue "title" in "myorg/myrepo"`  - creates issue without description 
* [x] used same syntax for "title" in `bot close milestone`
* [x] `bot create|close milestone` - returns exact link to the created|closed milestone
* [x] bot has a response for tags `+todo, +standup, +link`
# Tasks

* [x] remove `bot adapter` 0.05
* [x] remove extra type in `bot issue` 0.05
* [x] add new regex that matches the following sentence `bot issue "title" in "myorg/myrepo"` 0.5
* [x] refactore `bot issue` response to get exact url of issue 1
* [x] add response section to `bot +todo` and `bot +link`
* [x] `bot time in <place>` will return time in the specific place #65 
* [x] refactor `bot close milestone` to use same sytax for "title" 0.1
* [x] test it locally on `bot` channel 0.1
* [x] push to heroku 0.1

# Analysis

Add `robot.reply` method in `main.js` when `tags` succesfully processed with the message `todo successfully recorded`
`Bot issue ...` command will return a response with the exact location of the issue. For this implementation, I will use `github-api` library which we have already used in `issue.js` to get id.
All API calls can be found here: http://github-tools.github.io/github/
* For tags will have a response such as: 
```
+tag recorded
```

**Comment by Mikanebu** [comment]
FIXED, updated help message, `bot issue` responds with exact URL of the created issue, fixed some minor issues, plus, `bot isssue` can be called without body property
