### ISSUE TITLE
bot should respond with specific timezone, e.g., bot time almaty and it should return time in almaty

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#65]
We want to have our bot command to return specific time of place.

## Acceptance criteria 

* [x] `bot time in Almaty` returns local time in Almaty

## Tasks 

* [x] install `hubot-timezone`
* [x] test it locally on `bot` channel
* [x] deploy to heroku

## Analysis

Interesting libraries to try: 
https://www.npmjs.com/package/hubot-current-time
https://github.com/ryandao/hubot-timezone
I would like to use second library `hibot-timezone` since, it was no environmental variables, and it is easy to implement.

**Comment by Mikanebu** [comment]
FIXED
