### ISSUE TITLE
implement a command like `bot standups` and `+standup`

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#66]
implement a command like `bot standups` to show standup spreadsheet and support for `+standup` tag (to store into the standup spreadsheet - bonus points for parsing out last24 and next24 and blockers!)

## Acceptance criteria

* [x] `+standup` will be saved in Google Spreadsheet(new sheet for storing standups)
* [x] `bot standups` will return url for recorded Google Spreadsheet

## Tasks

* [x] create new sheet with the following headers: `action, timestamp, poster, standup`
* [x] add new statement into `messages.js` to catch `standup`
* [x] add function `getStandup` to `formatting.js` to parse `standup`
* [x] add elseif statement into `formatMessage` function in `messages.js` to use new format for `+standup`
* [x] `bot standups` returns url for Google Spreadsheet 
  * [x] add into new hear method into `main.js`
  * [x] write unittest
  * [x] test locally on `bot` channel
* [x] test locally on `bot` channel
* [x] write unittest
* [x] update `docs/help.md`
* [x] update `README.md`
* [x] push to heroku 

##Analysis

We can use setting in `config.json`, and change `messages.js` where we write to Google Spreadsheet. Plus, we need to refactor main.js so we can parse `last24` and `next24`, `blockers`. 

We need to create a new sheet in the same spreadsheet, with extra 3 columns which are `last24` and `next24`, `blockers`.
Since format of message is different, we also need to refactor old `formatMesssage` function. 
Refactor `formatting.js` to add new function to get `last24` and `next24`, `blockers`

`bot standups` implementation:
Add new function into `main.js`

**Comment by rufuspollock** [comment]
@Mikanebu one general question about our config.json - does his allow for +standup to go to a different document for each channel it is in i.e. if config were crude tabular form something like:

```
tag, channel, doctype, doc_url
-------------------------------
+standup, datopian/*, gdoc, https://....
+standup, artearthtech/*, gdoc, https:// 
```

**Comment by Mikanebu** [comment]
@rufuspollock for now, there is no channel property, I would like to test it but I need to analyse first. Let me create a separate issue for this.

**Comment by Mikanebu** [comment]
FIXED, opened new issue #70
