### ISSUE TITLE
misc improvements on todo command

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#67]
in a todo if no-one is assigned auto-assign to the person creating the todo

## Acceptance criteria

* [x] `+todo` will auto-assign to the person if no-one is mentioned

## Tasks 

* [x] refactor `message.js` 0.3
* [x] write unittest 0.3
* [x] test on `bot` channel 0.1
* [x] push to heroku 0.1

## Analysis

Refactor `messages.js` `formatMessage` function, include if statement for `assignees`
```
if assignees is not found, use assignees = poster
```

**Comment by Mikanebu** [comment]
FIXED, +todo will auto-assign to the person if no-one is mentioned
