### ISSUE TITLE
setup `channel` property into config.json

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#69]
One general question about our config.json - does his allow for +standup to go to a different document for each channel it is in i.e. if config were crude tabular form something like:

```
tag, channel, doctype, doc_url
-------------------------------
+standup, datopian/*, gdoc, https://....
+standup, artearthtech/*, gdoc, https:// 
```
## Acceptance criteria

* [x] bot hears `AET` channel and records to the appropriate google spreadsheet

## Tasks 

* [x] create new google spreadsheet or get Worksheet ID from the old 0.3
* [x] create new property `gdoc2` in `config.json` 1
* [x] refactor `main.js` to check for `room` name  1.5
* [x] write unittest 0.5
* [x] create test channel `AET/bot` and test it locally 0.1
* [x] push to heroku 0.1

## Analysis 

We can setup configuration in `config.json` by adding `gdoc2` property for `artearthtech` channel, `gdoc1` will be used only for `datopian` channel. 
Adding room names in `config.json` 
```
  "docs": {
        "gdoc1": {
            "fun": "sendMessage",
            "dest": "1w4LBF6wbRNVynAk8cQURyz8yZCbTw5hPwcqr87S46hY",
            "room": "artearthtech"
        },
        "gdoc2": {
            "fun": "sendMessage",
            "dest": "2b2875c259f5c41ee8ad6c447bd99667".
            "room": "datopian"
        }
    }
```
Also, we have to refactor login in `main.js`, when it hears for `+todo, +standup, +link` it will  check for `room.name` and so on.

**Comment by Mikanebu** [comment]
FIXED, now bot can hear channels and recorded them in appropriate Google Spreadsheets. Only `config.json` can be configured in the future
