### ISSUE TITLE
get google spreadsheet/sheet gid from google API

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#70]
For now Google Spreadsheet url is hardcoded in our bot script. We want to create it by Google API.

## Acceptance criteria

* [x] Google Spreadsheet url is not hardcoded
 
## Tasks

* [x] Use Google Api to get Google Spreadsheet `sheet gid`  1.5
* [x] refactor unittests  1.5
  * [x] mock API calls

## Analysis

I checked `google-spreadsheet` and `google-sheets-api`, and there is no option to get `gid` of the specific `sheet`. Probaby we can leave it hardcoded or We can give the `url` of the spreadsheet without point to the specific `sheet`

* using `google-spreadsheet` library, I can make a API call and get only using 
```
info.worksheets[0]._links['http://schemas.google.com/visualization/2008#visualizationApi
Output: 
https://docs.google.com/spreadsheets/d/1w4LBF6wbRNVynAk8cQURyz8yZCbTw5hPwcqr87S46hY/gviz/tq?gid=0
```
I can get `gid` of sheet from the abovementioned string

**Comment by zelima** [comment]
@Mikanebu we can not leave this hardcoded as there will be multiple rooms and multiple spreadsheets for different projects/rooms etc...

**Comment by Mikanebu** [comment]
FIXED, now there is no hardcoding, we use Google Spreadsheet API for getting `sheet gid`
