### ISSUE TITLE
Trello analysis

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#71]
We want to have an analysis on automating Trello functionality in our bot.

## Acceptance criteria

* [ ] Analysis on Trello functionality

## Tasks

* [ ] Write analysis on Trello functionality 
  * [ ] Possible command we can create such as `creating tasks, move tasks to appropriate statuses, show lists`
    * [ ] check this package [hubot-trello](https://github.com/hubot-scripts/hubot-trello)

## Analysis 

Interesting packages for trello functionality
https://github.com/hubot-scripts/hubot-trello

**Comment by rufuspollock** [comment]
DUPLICATE of #23.
