### ISSUE TITLE
Wrong due date for `bot create milestone`

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#72]
After running `bot create milestone` command, it created with due date earlier than in title.

## Acceptance criteria

* [ ] due date is correct for`bot create milestone` command

## Tasks 

* [x] see `moment` library
* [x] fix `milestone.js` to get exact time
* [x] test it in `bot` channel

## Analysis 

See [moment](https://www.npmjs.com/package/moment) for getting same time zone as in github uses

**Comment by Mikanebu** [comment]
FIXED, now it creates with correct due date
