### ISSUE TITLE
Demo to AET team

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#73]
We want to prepare a small presentation about our `bot` 

## Acceptance criteria

* [ ] AET team understands how to use bot commands and have tried themselves 

## Tasks

* [x] Schedule time with AET team 0.1
* [ ] Create a small presentation 1
* [x] Present to Viktoria and get feedback 1
* [x] Present to AET team 0.5

**Comment by Mikanebu** [comment]
FIXED, had a call with AET team, and did a quick demo on main functionality of the datopianbot like `+todo` `+standups` `+links` tags with screen sharing.
