### ISSUE TITLE
can you add support for tags +integrity and +promise to our tagging system please

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#82]
We want to record `+promise` and `+integrity` in our channels and add commands `bot promises` and `bot integrities` that return URL for recorded Google Spreadsheet

## Acceptance criteria

* [x] `+promise` and `+integrity` is recorded on Google Spreadsheet
* [x] `bot promises` returns URL for Google Spreadsheet
* [x] `bot integrities` returns URL for Google Spreadsheet

## Tasks

* [x] create new sheet `integrities` in Google Spreadsheet
* [x] crete new sheet `promises` in Google Spreadsheet
* [x] add properties into `config.json`
* [x] refactor `main.js` to hear command `bot promises` and `bot integrities`
* [x] write unittest
* [x] test on `bot` channel
* [x] push to heroku

### Tags
```
"monitor": {
        "+promise": {
            "action": "log",
            "dest": ["gdocDatopian","gdocArtErthTech"]
        },
        "+integrity": {
            "action": "log",
            "dest": ["gdocDatopian","gdocArtErthTech"]
        }
    },
```

### Commands

```
 robot.hear(/bot todos|bot standups|bot links|bot promises|bot integrities/i, res => {
    const tags = [
      {tag: '+todo', command: 'todos'},
      {tag: '+standup', command: 'standups'},
      {tag: '+link', command: 'links'},
      {tag: '+promise', command: 'promises'},
      {tag: '+integrity', command: 'integrities'}
    ]
...
```

**Comment by Mikanebu** [comment]
FIXED, added new tags `+promise` and `integrity`, also `bot promises` and `bot integrities` commands to get URL
