### ISSUE TITLE
add bot function to record daily "outcome" score (the 10 point system with 3 parts)

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#83]
We want to record daily `outcome` with total score of 10 points for the following parts: preparation(3 points), done(4points), satisfaction(3points). 

## Acceptance criteria

* [x] `+outcome` tag will record into spreadsheet
* [x] `bot outcomes` will return spreadsheet ulr for recorded `+outcome` tag

## Tasks

* [x] Analysis
* [x] Add new tag `+outcome`
* [x] Add new command `bot outcomes`
* [x] Update bot help message with new tag and command
* [x] Update `README.md` by adding new command and tag
* [x] Write unittests
* [x] Tested locally on `datopianbot` channel
* [x] Deploy to heroku

## Analysis
```
Points out of 10
* 3 points for doing prep and analysis (3 out of 3 = perfect, no corrections, on time etc)
* 7 points for performance =
  * 4 points for percentage you got done
  * 3 points for how you felt (you were well and balanced, content, challenged (positively), and not too tired)
```

I will suggest using `+outcome` tag with the following properties:
* for the percentage you got done: `done: 40%` || `done=40%`
* for doing prep and analysis: `prep:3` || `prep=3`
* for how you felt: `felt:3` || `felt=3`

Entire example would be:

```
+outcome done=30%, felt=3, prep=3
```
```
+outcome done:30%, felt:3, prep:3
```
After the discussion the final output:
`+outcome 100%, 75%, 100%`
Bot will respond the total score out of 10
`Outcome recorded: your score was 7.5/10`
Plus, add new command `bot outcomes` that returns spreadsheet URL for recorded outcomes.

**Comment by rufuspollock** [comment]
@Mikanebu i think we could simplify to:

+outcome 1,2,3

And people could do the help to work out the order. I think the order should be: prep, done, satisfaction/felt (because that is approximate order they happen in).

It would also be nice if the bot response added these up so it said:

Outcome recorded: your score was x/10.

**Comment by Mikanebu** [comment]
@rufuspollock Just want to clarify, +outcome prep=out of 3, done out of 3, satisfaction out of 100%. For example, `+outcome 1,1,50%`. The response would be something like `Outcome recorded: your score was 4/10`.

**Comment by rufuspollock** [comment]
ok, do it that way.

**Comment by Mikanebu** [comment]
people get confused with the points, so we will make them all in percentage. The order will be `+outcome 100%,75%,50%` - respectively prep, done, satisfaction

**Comment by Mikanebu** [comment]
FIXED, command `bot ourcomes`, tag `+outcome 100%,100%,100%` all params in percent and order is prep/analysis, done, satisfaction/felt`. The response will look like `Outcome recorded: your score was 8.5/10` with total score calculation
