### ISSUE TITLE
Add milestone option to bot issue command

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#86]
We want to have a milestone option for `bot issue`, so we can assign to the specific milestone or by default to `backlog`

## Acceptance criteria

* bot issue has an option to assign milestone

## Tasks

* [x] analysis
* [x] refactor current bot issue
* [x] add new bo issue with `milestone` option
* [x] write tests and test it locally
* [x] push to heroku 

## Analysis

The bot command would be like that to specify milestone
```
bot issue "title" in "myorg/myrepo" to "Sprint - 9 Oct 2017"
```
If you do not specify milestone, by default it would be in `backlog`, it will be the same command as bot issue:
```
bot issue "title" in "myorg/myrepo"
```
Refactor current `bot issue command` to assign in `backlog`
Add new hear function to listen for new regex 
```
bot issue "([^"]+)"?(?: in "([\w\d-_]+)(?:\/([\w\d-_]+))?") to "([^"]+)"
```
Plus, refactor `issue.js` to add property `milestone` into API call
```
const createIssue = (title, body, owner, repo, milestone) => {
  const issueObj = new Issue(owner + '/' + repo, {token:token})
  const issueData = {
    title,
    body,
    milestone
  }
  return issueObj.createIssue(issueData)
}
```

**Comment by Mikanebu** [comment]
FIXED,  now you can assign issue into specific milestone or by default it will be assigned into backlog
