### ISSUE TITLE
added new tag +feedback and command bot feedback

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#92]
We want to record feedback in our channels

## Acceptance criteria

* [x] `+feedback` tag will record into spreadsheet
* [x] `bot feedback` will return spreadsheet ulr for recorded `+feedback` tag

## Tasks

* [x] Analysis
* [x] Add new tag `+feedback`
* [x] Add new command `bot feedback`
* [x] Update bot help message with new tag and command
* [x] Update `README.md` by adding new command and tag
* [x] Write unittests
* [x] Tested locally on `datopianbot` channel
* [x] Deploy to heroku

## Analysis

Columns will be the following:
`action,timestamp,poster,assignees,message,room`

**Comment by Mikanebu** [comment]
FIXED, now bot records new tag `+feedback`, and responds with gdoc url for command `bot feedback`
