### ISSUE TITLE
add new tag +break, and command bot breaks

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#94]
We want to record break time for our team with +break tag, so we will know who is not online. 

## Acceptance criteria

* [ ] `+break` tag will record into spreadsheet
* [ ] `bot breaks` will return spreadsheet ulr for recorded `+break` tag

## Tasks

* [ ] Analysis
* [ ] Add new tag `+break`
* [ ] Add new command `bot breaks`
* [ ] Update bot help message with new tag and command
* [ ] Update `README.md` by adding new command and tag
* [ ] Write unittests
* [ ] Tested locally on `datopianbot` channel
* [ ] Deploy to heroku
