### ISSUE TITLE
add new tag +learning, and command bot learnings

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#95]
We want to record learnings using +learning tag. 

## Acceptance criteria

* [ ] `+learning` tag will record into spreadsheet
* [ ] `bot learnings` will return spreadsheet ulr for recorded `+learning` tag

## Tasks

* [ ] Analysis
* [ ] Add new tag `+learning`
* [ ] Add new command `bot learnings`
* [ ] Update bot help message with new tag and command
* [ ] Update `README.md` by adding new command and tag
* [ ] Write unittests
* [ ] Tested locally on `datopianbot` channel
* [ ] Deploy to heroku
