### ISSUE TITLE
'bot todos' command - I want the bot to print my todos directly in the chat

### ISSUE THREAD

**Issue by AcckiyGerman** [datopian/ourbot#96]
As a busy developer I want to see my todos directly in the chat, so I'm wasting time exploring the google document.

## Acceptance Criteria
* [ ] 'bot todos' returns the list of todos related to the person, who called the command.

## Tasks
* [] discuss the feature with the bot author
---
* [] add tests for the tasks below. (TDD - tests then code)
* [] parse datopian-chat-log to find all tasks related to the caller
* [] print the task list into the chat
* [] update the bot help section
* ??? [] should bot print the link to the document then, if we already have the todo list?
## Analysis
In the future, as we have the task list in front of eyes, we could type something like:
bot todos [index] close [result: fixed, wontfix, etc]

**Comment by Mikanebu** [comment]
@AcckiyGerman Thanks for your suggestion. I will do analysis for this case. Yes, it is better to have a separate command like `bot todos show` and get list of todos where status is not `processed` for the user

**Comment by Branko-Dj** [comment]
I would also very much like to take a look at this
