### ISSUE TITLE
Update config.json

### ISSUE THREAD

**Issue by zelima** [datopian/ourbot#99]
We have added a bunch of repos since config.json was last modified. Meaning not all repos are included in `bot create/close milestone all`.

## Acceptance Criteria

* [ ] config.json is up to date and **all** datahq repos are listed there (Plus probably this repo)

## Tasks

* [ ] List all the repos we have
* [ ] Update config.json
